// flow-typed signature: 6612cf2a2b1b1c1d743aaa762e116ee9
// flow-typed version: <<STUB>>/blob-stream_v^0.1.3/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blob-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'blob-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blob-stream/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blob-stream/index' {
  declare module.exports: $Exports<'blob-stream'>;
}
declare module 'blob-stream/index.js' {
  declare module.exports: $Exports<'blob-stream'>;
}
declare module 'blob-stream/test/index.js' {
  declare module.exports: $Exports<'blob-stream/test/index'>;
}
