// flow-typed signature: 9414e6091c3e040ccb828a902753356d
// flow-typed version: <<STUB>>/http-proxy-middleware_v0.17.1/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-proxy-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-proxy-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-proxy-middleware/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/examples/browser-sync/index' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/examples/connect/index' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/examples/express/index' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/examples/websocket/index' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/config-factory' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/context-matcher' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/handlers' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/logger' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/path-rewriter' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-proxy-middleware/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'http-proxy-middleware/coverage/lcov-report/prettify'>;
}
declare module 'http-proxy-middleware/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'http-proxy-middleware/coverage/lcov-report/sorter'>;
}
declare module 'http-proxy-middleware/examples/browser-sync/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware/examples/browser-sync/index'>;
}
declare module 'http-proxy-middleware/examples/connect/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware/examples/connect/index'>;
}
declare module 'http-proxy-middleware/examples/express/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware/examples/express/index'>;
}
declare module 'http-proxy-middleware/examples/websocket/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware/examples/websocket/index'>;
}
declare module 'http-proxy-middleware/index' {
  declare module.exports: $Exports<'http-proxy-middleware'>;
}
declare module 'http-proxy-middleware/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware'>;
}
declare module 'http-proxy-middleware/lib/config-factory.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/config-factory'>;
}
declare module 'http-proxy-middleware/lib/context-matcher.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/context-matcher'>;
}
declare module 'http-proxy-middleware/lib/handlers.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/handlers'>;
}
declare module 'http-proxy-middleware/lib/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/index'>;
}
declare module 'http-proxy-middleware/lib/logger.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/logger'>;
}
declare module 'http-proxy-middleware/lib/path-rewriter.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/path-rewriter'>;
}
declare module 'http-proxy-middleware/lib/router.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/router'>;
}
