// flow-typed signature: 64c9af83267aed1c5172117b05168666
// flow-typed version: <<STUB>>/pdfmake_v^0.1.18/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdfmake'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdfmake' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdfmake/dev-playground/public/ace' {
  declare module.exports: any;
}

declare module 'pdfmake/dev-playground/public/playground' {
  declare module.exports: any;
}

declare module 'pdfmake/dev-playground/server' {
  declare module.exports: any;
}

declare module 'pdfmake/Gruntfile' {
  declare module.exports: any;
}

declare module 'pdfmake/gulpfile' {
  declare module.exports: any;
}

declare module 'pdfmake/libs/fileSaver' {
  declare module.exports: any;
}

declare module 'pdfmake/src/columnCalculator' {
  declare module.exports: any;
}

declare module 'pdfmake/src/docMeasure' {
  declare module.exports: any;
}

declare module 'pdfmake/src/documentContext' {
  declare module.exports: any;
}

declare module 'pdfmake/src/elementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/src/fontProvider' {
  declare module.exports: any;
}

declare module 'pdfmake/src/fontWrapper' {
  declare module.exports: any;
}

declare module 'pdfmake/src/helpers' {
  declare module.exports: any;
}

declare module 'pdfmake/src/imageMeasure' {
  declare module.exports: any;
}

declare module 'pdfmake/src/layoutBuilder' {
  declare module.exports: any;
}

declare module 'pdfmake/src/line' {
  declare module.exports: any;
}

declare module 'pdfmake/src/pageElementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/src/printer' {
  declare module.exports: any;
}

declare module 'pdfmake/src/qrEnc' {
  declare module.exports: any;
}

declare module 'pdfmake/src/standardPageSizes' {
  declare module.exports: any;
}

declare module 'pdfmake/src/styleContextStack' {
  declare module.exports: any;
}

declare module 'pdfmake/src/tableProcessor' {
  declare module.exports: any;
}

declare module 'pdfmake/src/textDecorator' {
  declare module.exports: any;
}

declare module 'pdfmake/src/textTools' {
  declare module.exports: any;
}

declare module 'pdfmake/src/traversalTracker' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/browser-extensions/base64' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/browser-extensions/pdfMake' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/browser-extensions/virtual-fs' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/columnCalculator' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/docMeasure' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/documentContext' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/elementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/fontProvider' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/fontWrapper' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/helpers' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/imageMeasure' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/layoutBuilder' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/line' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/pageElementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/printer' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/qrEnc' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/standardPageSizes' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/styleContextStack' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/tableProcessor' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/textDecorator' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/textTools' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/src/traversalTracker' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/columnCalculator' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/docMeasure' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/documentContext' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/elementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/fontWrapper' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/alignment' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/background' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/basics' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/columns' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/images' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/integrationTestHelper' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/lists' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/integration/tables' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/layoutBuilder' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/line' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/pageElementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/printer' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/styleContextStack' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/tableProcessor' {
  declare module.exports: any;
}

declare module 'pdfmake/test-env/tests/textTools' {
  declare module.exports: any;
}

declare module 'pdfmake/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdfmake/dev-playground/public/ace.js' {
  declare module.exports: $Exports<'pdfmake/dev-playground/public/ace'>;
}
declare module 'pdfmake/dev-playground/public/playground.js' {
  declare module.exports: $Exports<'pdfmake/dev-playground/public/playground'>;
}
declare module 'pdfmake/dev-playground/server.js' {
  declare module.exports: $Exports<'pdfmake/dev-playground/server'>;
}
declare module 'pdfmake/Gruntfile.js' {
  declare module.exports: $Exports<'pdfmake/Gruntfile'>;
}
declare module 'pdfmake/gulpfile.js' {
  declare module.exports: $Exports<'pdfmake/gulpfile'>;
}
declare module 'pdfmake/libs/fileSaver.js' {
  declare module.exports: $Exports<'pdfmake/libs/fileSaver'>;
}
declare module 'pdfmake/src/columnCalculator.js' {
  declare module.exports: $Exports<'pdfmake/src/columnCalculator'>;
}
declare module 'pdfmake/src/docMeasure.js' {
  declare module.exports: $Exports<'pdfmake/src/docMeasure'>;
}
declare module 'pdfmake/src/documentContext.js' {
  declare module.exports: $Exports<'pdfmake/src/documentContext'>;
}
declare module 'pdfmake/src/elementWriter.js' {
  declare module.exports: $Exports<'pdfmake/src/elementWriter'>;
}
declare module 'pdfmake/src/fontProvider.js' {
  declare module.exports: $Exports<'pdfmake/src/fontProvider'>;
}
declare module 'pdfmake/src/fontWrapper.js' {
  declare module.exports: $Exports<'pdfmake/src/fontWrapper'>;
}
declare module 'pdfmake/src/helpers.js' {
  declare module.exports: $Exports<'pdfmake/src/helpers'>;
}
declare module 'pdfmake/src/imageMeasure.js' {
  declare module.exports: $Exports<'pdfmake/src/imageMeasure'>;
}
declare module 'pdfmake/src/layoutBuilder.js' {
  declare module.exports: $Exports<'pdfmake/src/layoutBuilder'>;
}
declare module 'pdfmake/src/line.js' {
  declare module.exports: $Exports<'pdfmake/src/line'>;
}
declare module 'pdfmake/src/pageElementWriter.js' {
  declare module.exports: $Exports<'pdfmake/src/pageElementWriter'>;
}
declare module 'pdfmake/src/printer.js' {
  declare module.exports: $Exports<'pdfmake/src/printer'>;
}
declare module 'pdfmake/src/qrEnc.js' {
  declare module.exports: $Exports<'pdfmake/src/qrEnc'>;
}
declare module 'pdfmake/src/standardPageSizes.js' {
  declare module.exports: $Exports<'pdfmake/src/standardPageSizes'>;
}
declare module 'pdfmake/src/styleContextStack.js' {
  declare module.exports: $Exports<'pdfmake/src/styleContextStack'>;
}
declare module 'pdfmake/src/tableProcessor.js' {
  declare module.exports: $Exports<'pdfmake/src/tableProcessor'>;
}
declare module 'pdfmake/src/textDecorator.js' {
  declare module.exports: $Exports<'pdfmake/src/textDecorator'>;
}
declare module 'pdfmake/src/textTools.js' {
  declare module.exports: $Exports<'pdfmake/src/textTools'>;
}
declare module 'pdfmake/src/traversalTracker.js' {
  declare module.exports: $Exports<'pdfmake/src/traversalTracker'>;
}
declare module 'pdfmake/test-env/src/browser-extensions/base64.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/browser-extensions/base64'>;
}
declare module 'pdfmake/test-env/src/browser-extensions/pdfMake.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/browser-extensions/pdfMake'>;
}
declare module 'pdfmake/test-env/src/browser-extensions/virtual-fs.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/browser-extensions/virtual-fs'>;
}
declare module 'pdfmake/test-env/src/columnCalculator.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/columnCalculator'>;
}
declare module 'pdfmake/test-env/src/docMeasure.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/docMeasure'>;
}
declare module 'pdfmake/test-env/src/documentContext.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/documentContext'>;
}
declare module 'pdfmake/test-env/src/elementWriter.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/elementWriter'>;
}
declare module 'pdfmake/test-env/src/fontProvider.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/fontProvider'>;
}
declare module 'pdfmake/test-env/src/fontWrapper.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/fontWrapper'>;
}
declare module 'pdfmake/test-env/src/helpers.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/helpers'>;
}
declare module 'pdfmake/test-env/src/imageMeasure.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/imageMeasure'>;
}
declare module 'pdfmake/test-env/src/layoutBuilder.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/layoutBuilder'>;
}
declare module 'pdfmake/test-env/src/line.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/line'>;
}
declare module 'pdfmake/test-env/src/pageElementWriter.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/pageElementWriter'>;
}
declare module 'pdfmake/test-env/src/printer.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/printer'>;
}
declare module 'pdfmake/test-env/src/qrEnc.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/qrEnc'>;
}
declare module 'pdfmake/test-env/src/standardPageSizes.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/standardPageSizes'>;
}
declare module 'pdfmake/test-env/src/styleContextStack.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/styleContextStack'>;
}
declare module 'pdfmake/test-env/src/tableProcessor.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/tableProcessor'>;
}
declare module 'pdfmake/test-env/src/textDecorator.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/textDecorator'>;
}
declare module 'pdfmake/test-env/src/textTools.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/textTools'>;
}
declare module 'pdfmake/test-env/src/traversalTracker.js' {
  declare module.exports: $Exports<'pdfmake/test-env/src/traversalTracker'>;
}
declare module 'pdfmake/test-env/tests/columnCalculator.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/columnCalculator'>;
}
declare module 'pdfmake/test-env/tests/docMeasure.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/docMeasure'>;
}
declare module 'pdfmake/test-env/tests/documentContext.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/documentContext'>;
}
declare module 'pdfmake/test-env/tests/elementWriter.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/elementWriter'>;
}
declare module 'pdfmake/test-env/tests/fontWrapper.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/fontWrapper'>;
}
declare module 'pdfmake/test-env/tests/integration/alignment.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/alignment'>;
}
declare module 'pdfmake/test-env/tests/integration/background.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/background'>;
}
declare module 'pdfmake/test-env/tests/integration/basics.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/basics'>;
}
declare module 'pdfmake/test-env/tests/integration/columns.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/columns'>;
}
declare module 'pdfmake/test-env/tests/integration/images.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/images'>;
}
declare module 'pdfmake/test-env/tests/integration/integrationTestHelper.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/integrationTestHelper'>;
}
declare module 'pdfmake/test-env/tests/integration/lists.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/lists'>;
}
declare module 'pdfmake/test-env/tests/integration/tables.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/integration/tables'>;
}
declare module 'pdfmake/test-env/tests/layoutBuilder.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/layoutBuilder'>;
}
declare module 'pdfmake/test-env/tests/line.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/line'>;
}
declare module 'pdfmake/test-env/tests/pageElementWriter.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/pageElementWriter'>;
}
declare module 'pdfmake/test-env/tests/printer.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/printer'>;
}
declare module 'pdfmake/test-env/tests/styleContextStack.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/styleContextStack'>;
}
declare module 'pdfmake/test-env/tests/tableProcessor.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/tableProcessor'>;
}
declare module 'pdfmake/test-env/tests/textTools.js' {
  declare module.exports: $Exports<'pdfmake/test-env/tests/textTools'>;
}
declare module 'pdfmake/webpack.config.js' {
  declare module.exports: $Exports<'pdfmake/webpack.config'>;
}
