// flow-typed signature: ae5911c81c186f4b7101a81d12eceb20
// flow-typed version: <<STUB>>/react-autocomplete_v^1.3.1/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-autocomplete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-autocomplete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-autocomplete/build/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-autocomplete/build/lib/index' {
  declare module.exports: any;
}

declare module 'react-autocomplete/build/lib/utils' {
  declare module.exports: any;
}

declare module 'react-autocomplete/dist/react-autocomplete' {
  declare module.exports: any;
}

declare module 'react-autocomplete/dist/react-autocomplete.min' {
  declare module.exports: any;
}

declare module 'react-autocomplete/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-autocomplete/lib/index' {
  declare module.exports: any;
}

declare module 'react-autocomplete/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-autocomplete/build/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-autocomplete/build/lib/Autocomplete'>;
}
declare module 'react-autocomplete/build/lib/index.js' {
  declare module.exports: $Exports<'react-autocomplete/build/lib/index'>;
}
declare module 'react-autocomplete/build/lib/utils.js' {
  declare module.exports: $Exports<'react-autocomplete/build/lib/utils'>;
}
declare module 'react-autocomplete/dist/react-autocomplete.js' {
  declare module.exports: $Exports<'react-autocomplete/dist/react-autocomplete'>;
}
declare module 'react-autocomplete/dist/react-autocomplete.min.js' {
  declare module.exports: $Exports<'react-autocomplete/dist/react-autocomplete.min'>;
}
declare module 'react-autocomplete/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-autocomplete/lib/Autocomplete'>;
}
declare module 'react-autocomplete/lib/index.js' {
  declare module.exports: $Exports<'react-autocomplete/lib/index'>;
}
declare module 'react-autocomplete/lib/utils.js' {
  declare module.exports: $Exports<'react-autocomplete/lib/utils'>;
}
